### ISSUE TITLE
Update SQL scripts from SDK1 to SDK2

### ISSUE THREAD

**Issue by aguzev** [PureStorage-OpenConnect/powershell-toolkit-3#1]
https://github.com/PureStorage-OpenConnect/sqlserver-scripts

#### Scripts to update:
- [x] Deploy-SQL-Server-VM GH-31
- [x] Refresh-Dev-Environment GH-2 GH-31
- [x] Refresh-Dev-From-VMDK-V2  GH-31
- [x] Refresh-Dev-From-VMDK GH-31
- [x] Refresh-Dev-On-Cluster GH-31
- [x] Refresh-Dev-ProtectionGroups-vVol-v2 GH-31
- [x] Refresh-Dev-ProtectionGroups-vVol-v3 GH-31
- [x] Refresh-Dev-ProtectionGroups-vVol GH-31
- [x] Refresh-Dev-ProtectionGroups GH-31
- [x] Refresh-Dev-PsFunc  GH-31
- [x] Refresh-DR GH-3 GH-31
