### ISSUE TITLE
Create Exchange module

### ISSUE THREAD

**Issue by aguzev** [PureStorage-OpenConnect/powershell-toolkit-3#10]
Take Q's Exchange module and productize it, clean it up, convert to sdk2, make it a toolkit dependency, and publish on GitHub/psgallery.

- [x] New-ExchBackup GH-19 GH-36
- [x] Get-ExchBackup GH-36
- [x] Restore-ExchBackup GH-36
- [x] Remove-ExchBackup GH-36
- [x] Expose-ExchBackup GH-36
